---
- name: Configuration Post-Déploiement FOG
  hosts: localhost
  connection: local
  become: yes

  vars:
    # On peut définir des variables ici ou dans group_vars/all.yml
    sys_packages: [ 'firefox', 'curl', 'git', 'vim', 'htop', 'vlc' ]

  roles:
    - common
    # On peut ajouter une condition pour n'installer le rôle desktop 
    # que si une interface graphique est détectée
