---
- name: Mise à jour du système
  apt:
    update_cache: yes
    upgrade: dist

- name: Installation de logiciels de base
  apt:
    name:
      - vim
      - curl
      - htop
      - vlc
    state: present
