---
- name: Mise à jour du cache APT
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installation des paquets système
  apt:
    name: "{{ sys_packages }}"
    state: present

- name: Configuration du fuseau horaire
  timezone:
    name: "Europe/Paris"

- name: Personnalisation du message d'accueil (MOTD)
  copy:
    content: "Machine deployée par Hicham-FOG le {{ ansible_date_time.date }}\n"
    dest: /etc/motd
